add_newline = true

[username]
disabled = false
show_always = true

[sudo]
symbol = " "
disabled = false
style = "bold red"

[cmd_duration]
style = "green"
format = "took [$duration]($style) "

[directory]
truncation_length=1
read_only = " "
home_symbol = " ~ "

[package]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "
python_binary = "python3"
style = "blue"

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
symbol = " "

[git_branch]
symbol = " "
